apiVersion: apps/v1
kind: Deployment
metadata:
  name: anoti-conformity-analyzer
spec:
  selector:
    matchLabels:
      app: anoti-conformity-analyzer
  template:
    metadata:
      labels:
        app: anoti-conformity-analyzer
    spec:
      containers:
      - name: anoti-conformity-analyzer
        image: 250956544061.dkr.ecr.eu-west-3.amazonaws.com/anoti-conformity-analyzer:4.0.2
        imagePullPolicy: Always
        tty: true
        env:
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: anoti-mongo-mongodb
                key: mongodb-root-password
        envFrom:
        - configMapRef:
            name: anoti-nats-client-config
        - configMapRef:
            name: anoti-mongo-config
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        resources:
          requests:
            memory: "2048Mi"
            cpu: "3.5"
          limits:
            memory: "3500Mi"
            cpu: "3.9"
      nodeSelector:
        "node.kubernetes.io/instance-type": "c6g.xlarge"