apiVersion: apps/v1
kind: Deployment
metadata:
  name: anoti-conformity-analyzer
spec:
  selector:
    matchLabels:
      app: anoti-conformity-analyzer
  template:
    metadata:
      labels:
        app: anoti-conformity-analyzer
    spec:
      containers:
      - name: anoti-conformity-analyzer
        image: 250956544061.dkr.ecr.eu-west-3.amazonaws.com/anoti-conformity-analyzer:1.1.0
        imagePullPolicy: Always
        tty: true
        envFrom:
        - configMapRef:
            name: anoti-kafka-client-config
        env:
        - name: KAFKA_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: anoti-kafka-user-passwords
              key: client-passwords
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        resources:
          requests:
            memory: "2048Mi"
            cpu: "0.5"
          limits:
            memory: "3500Mi"
            cpu: "0.9"
