apiVersion: apps/v1
kind: Deployment
metadata:
  name: anoti-conformity-endpoints
spec:
  selector:
    matchLabels:
      app: anoti-conformity-endpoints
  template:
    metadata:
      labels:
        app: anoti-conformity-endpoints
    spec:
      containers:
      - name: anoti-conformity-endpoints
        image: 250956544061.dkr.ecr.eu-west-3.amazonaws.com/anoti-conformity-endpoints:3.0.3
        imagePullPolicy: Always
        tty: true
        env:
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: anoti-mongo-mongodb
                key: mongodb-root-password
        envFrom:
        - configMapRef:
            name: anoti-nats-client-config
        - configMapRef:
            name: anoti-mongo-config
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 5
          periodSeconds: 15
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        resources:
          requests:
            memory: "1024Mi"
            cpu: "0.5"
          limits:
            memory: "2048Mi"
            cpu: "0.9"
      nodeSelector:
        "node.kubernetes.io/instance-type": "t3.medium"