apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anoti-conformity-endpoints-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: anoti-conformity-endpoints-clusterip
            port:
              number: 8080
